name: C/C++ CI

on:
  [push, pull_request]

jobs:
  windows:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        configuration: [Debug, Release]
        platform: [Win32, x64]
    env:
      build_dir: ./src/build
    steps:
    - uses: actions/checkout@v2
    - name: prepare
      run: mkdir ${{ env.build_dir }}
    #- uses: actions/cache@v1
    #  name: Restore cache
    #  with:
    #    path: src/build
    #    key: ${{ runner.os }}-${{ matrix.platform }}-${{ matrix.configuration }}-${{ hashFiles('**/CMakeLists.txt') }}
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.0    
    - name: configure
      working-directory: ${{ env.build_dir }}
      run: cmake .. -DCMAKE_BUILD_TYPE=${{ matrix.configuration }} -A ${{ matrix.platform }} -Dautomaton_STATIC_RUNTIME=OFF -DCMAKE_INSTALL_PREFIX=../local_third_party
      shell: cmd
    - name: build
      working-directory: ${{ env.build_dir }}
      run: msbuild /t:Build INSTALL.vcxproj /p:Configuration=${{ matrix.configuration }} /p:Platform=${{ matrix.platform }}
      shell: cmd
    - name: test
      working-directory: ${{ env.build_dir }}
      run: ctest -j4 -C ${{ matrix.configuration }}
      shell: cmd
    - uses: actions/upload-artifact@v1
      with:
        name: ${{ matrix.configuration }}-${{ matrix.platform }}
        path: src/local_third_party
  ubuntu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        configuration: [Debug, Release]
    env:
      build_dir: ./src/build
    steps:
    - uses: actions/checkout@v2
    - name: prepare
      run: mkdir ${{ env.build_dir }}
    - name: configure
      working-directory: ${{ env.build_dir }}
      run: cmake .. -DCMAKE_BUILD_TYPE=${{ matrix.configuration }} -DCMAKE_INSTALL_PREFIX=../local_third_party
    - name: build
      working-directory: ${{ env.build_dir }}
      run: make install
    - name: test
      working-directory: ${{ env.build_dir }}
      run: ctest -j4 -C ${{ matrix.configuration }}
    - uses: actions/upload-artifact@v1
      with:
        name: ${{ matrix.configuration }}
        path: src/local_third_party
  macos:
    runs-on: macos-latest
    strategy:
      matrix:
        configuration: [Debug, Release]
    env:
      build_dir: ./src/build
      lint_dir: ./src/automaton
    steps:
    - uses: actions/checkout@v2
    - name: Install build dependencies
      run: brew install autoconf automake libtool
    - name: prepare
      run: mkdir ${{ env.build_dir }}
    - name: configure
      working-directory: ${{ env.build_dir }}
      run: cmake .. -DCMAKE_BUILD_TYPE=${{ matrix.configuration }} -DCMAKE_INSTALL_PREFIX=../local_third_party
    - name: build
      working-directory: ${{ env.build_dir }}
      run: make install
    - name: test
      working-directory: ${{ env.build_dir }}
      run: ctest -j4 -C ${{ matrix.configuration }}
    - uses: actions/upload-artifact@v1
      with:
        name: ${{ matrix.configuration }}
        path: src/local_third_party
  lint:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run lint checks
        run: ./lint.sh
        working-directory: ./src/automaton
